language: php
php: '7.0'
before_install:
  - npm install -g @lhci/cli@0.3.x # install LHCI
script: skip
after_success:
  - lhci collect url="http://localhost:4565/index.html"
deploy:
  provider: heroku
  api_key: d91bd977-9f11-4242-8c04-dbc145306b30
  app: lighthouse-ci-demo